---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-order-book-pv-trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-order-book
  template:
    metadata:
      labels:
        app: limit-order-book
    spec:
      imagePullSecrets:
        - name: amagnu-docker-secret
      containers:
        - name: limit-order-book
          image: limit-order-book:1.36
          ports:
            - containerPort: 3000
          env:
            - name: LOGFILE
              valueFrom:
                configMapKeyRef:
                  key: logfile
                  name: logfile
            - name: TRADES
              valueFrom:
                configMapKeyRef:
                  key: trades
                  name: trades
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: ps_host
                  name: postgres-config
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: ps_port
                  name: postgres-config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: ps_db
                  name: postgres-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: ps_user
                  name: postgres-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ps_password
                  name: postgres-secret
          volumeMounts:
            - name: trade-storage
              mountPath: /app/trades
      volumes:
        - name: trade-storage
          persistentVolumeClaim:
            claimName: trade-pvc
