apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-limit-order-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-limit-order-book
  template:
    metadata:
      labels:
        app: kubernetes-limit-order-book
    spec:
      containers:
      - name: limit-order-book
        image: limit-order-book:1.3
        ports:
        - containerPort: 3000
        env:
        - name: LOGFILE
          valueFrom:
            configMapKeyRef:
              key: logfile
              name: logfile
